CC = mipsel-linux-gcc

CFLAGS = -Ofast -Wall -I./WRAPPER -DSOUND_ENABLED
LDFLAGS = `sdl-config --cflags --libs` -lSDL_mixer
DEFINES = -DSOUND_ENABLED
OUTPUT = violent

SOURCES = src/main.c WRAPPER/GCW.c
OBJS = ${SOURCES:.c=.o}

${OUTPUT}:${OBJS}
	${CC} -o ${OUTPUT} ${SOURCES} ${CFLAGS} ${LDFLAGS} ${DEFINES} 
	
clean:
	rm src/*.o
	rm WRAPPER/*.o
	rm ${OUTPUT}
