CC = gcc

CFLAGS = -Ofast -I./WRAPPER
LDFLAGS = -static-libgcc -lSDL2 -lSDL2_mixer -lSDL2_image -pthread 
DEFINES = -DSOUND_ENABLED
OUTPUT = violent.elf

SOURCES = src/main.c WRAPPER/PC_SDL2.c
OBJS = ${SOURCES:.c=.o}

${OUTPUT}:${OBJS}
	${CC} -o ${OUTPUT} ${SOURCES} ${CFLAGS} ${LDFLAGS} ${DEFINES} 
	
clean:
	rm *.o ./src/*.o ./WRAPPER/*.o ${OUTPUT}
