CC = arm-cegcc-gcc

CFLAGS = -Os -I/opt/cegcc/arm-cegcc/include/ -I/opt/cegcc/arm-cegcc/include/SDL/  -I./WRAPPER
LDFLAGS =  -static -L/opt/cegcc/lib/ /opt/cegcc/lib/SDL_mixer.dll /opt/cegcc/lib/SDL.dll -lstdc++ -lm
DEFINES = -DSOUND_ENABLED
OUTPUT = violent

SOURCES = src/main.c WRAPPER/GIZ.c
OBJS = ${SOURCES:.c=.o}

${OUTPUT}:${OBJS}
	${CC} -o ${OUTPUT} ${SOURCES} ${CFLAGS} ${LDFLAGS} ${DEFINES} 
	arm-cegcc-strip ${OUTPUT}
	
clean:
	rm src/*.o
	rm WRAPPER/*.o
	rm ${OUTPUT}
